const GameActionTypes = {
    NEW_GAME: 'NEW_GAME',
    UPDATE_GAME: 'UPDATE_GAME',
    UPDATE_PLAYER_POSITIONS: 'UPDATE_PLAYER_POSITIONS',
    CALCULATE_VALID_MOVES: 'CALCULATE_VALID_MOVES',
    ON_PLAYER_MOVE: 'ON_PLAYER_MOVE',
    ON_CLICK: 'ON_CLICK',
    ON_ERROR: 'ON_ERROR',
}
export default GameActionTypes;


